### ISSUE TITLE
VS compile errors

### ISSUE THREAD

**Issue by sienaiwun** [sztomi/constexpr_murmurhash#1]
1. There are errors when compiling constexpr_murmurhash in VS2015, Update3. Such as
 error C3250: 'i': declaration is not allowed in 'constexpr' function body
 error C3249: illegal statement or sub-expression for 'constexpr' function
2. In VS2017 I can use constexpr_murmurharsh like
 ```
uint32_t out = mm3_x86_32("test", 0x9747b28c); 
 ```
 
 But There is a error when I use constexpr_murmurharsh like
  ```
constexpr uint32_t out = mm3_x86_32("test", 0x9747b28c); 
 ```
 
 The error message is :
error C4308: negative integral constant converted to unsigned type

**Comment by sztomi** [comment]
1. Yeah, VS2015 doesn't really have support for the relaxed constexpr, so this is expected.

2. ugh, I've no idea why that happenns, tbh. Could still be a VS incompatibility.
